name: Build .NET Project

on: [push, pull_request]

jobs:
  setup-dotnet:
    uses: ./.github/workflows/dotnet.yml

  build:
    name: Build Solution
    runs-on: ubuntu-latest
    needs: setup-dotnet

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build solution
        run: dotnet build --no-restore --configuration Release
