name: Code Coverage

on: [push, pull_request]

jobs:
  setup-dotnet:
    uses: ./.github/workflows/dotnet.yml

  code-coverage:
    if: github.actor != 'nektos/act'
    name: Code Coverage
    runs-on: ubuntu-latest
    needs: setup-dotnet

    steps:
      - name: Run tests with coverage
        run: |
          dotnet test --collect:"XPlat Code Coverage" --results-directory coverage/

      - name: Install ReportGenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool

      - name: Convert coverage to LCOV
        run: |
          reportgenerator \
            -reports:coverage/**/coverage.cobertura.xml \
            -targetdir:coverage-report \
            -reporttypes:lcov

      - name: Upload to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage-report/lcov.info
          debug: true

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage
          path: coverage-report
